name = "ModelObjectsLH"
uuid = "41cbb5d9-4a7a-4d38-8546-f9486737fd3b"
authors = ["hendri54 <hendricksl@protonmail.com>"]
version = "0.1.3"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
